services:
  - type: static
    name: frontend
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: dist
    headers:
      - source: "**"
        headers:
          - key: "Cache-Control"
            value: "public, max-age=0, must-revalidate"
    redirects:
      - source: "/**"
        destination: "/index.html"
        type: 200
